services:
  mysql:      
      image: mysql/mysql-server
      volumes:
      - db-volume:/var/lib/mysql
      environment:
        MYSQL_DATABASE: develop
        MYSQL_ROOT_PASSWORD: 12345
      
  
  hexagonal-calculator:
    image: image/hexagonal-calculator:1.0
    container_name: hexagonal-calculator
    command: ["dotnet", "CalculatorHexagonal.Runner.dll"]
    environment:
      - ASPNETCORE_ENVIRONMENT=Production 
      - DB_CONNECTION=Server=mysql;port=3306;Database=develop;User=root;Password=12345;
    stdin_open: true
    tty: true        
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 128M   
    depends_on:
      - mysql 
    
volumes:
  db-volume: 
